"""Initial migration with explicit constraint names

Revision ID: 261261c6e759
Revises: 
Create Date: 2024-11-22 13:31:23.306420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261261c6e759'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=15), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_phone'), ['phone'], unique=True)
        batch_op.create_unique_constraint('uq_user_email', ['email'])
        batch_op.create_unique_constraint('uq_user_phone', ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_phone', type_='unique')
        batch_op.drop_constraint('uq_user_email', type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_phone'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_column('phone')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
